./EmotionRecognizationClassifier.exe -t 0 train_1_2.txt test_1_2.txt >>result_0_1_2.txt
./EmotionRecognizationClassifier.exe -t 0 train_1_3.txt test_1_3.txt >>result_0_1_3.txt 
./EmotionRecognizationClassifier.exe -t 0 train_1_4.txt test_1_4.txt >>result_0_1_4.txt
./EmotionRecognizationClassifier.exe -t 0 train_1_5.txt test_1_5.txt >>result_0_1_5.txt
./EmotionRecognizationClassifier.exe -t 0 train_1_6.txt test_1_6.txt >>result_0_1_6.txt
./EmotionRecognizationClassifier.exe -t 0 train_2_3.txt test_2_3.txt >>result_0_2_3.txt
./EmotionRecognizationClassifier.exe -t 0 train_2_4.txt test_2_4.txt >>result_0_2_4.txt
./EmotionRecognizationClassifier.exe -t 0 train_2_5.txt test_2_5.txt >>result_0_2_5.txt
./EmotionRecognizationClassifier.exe -t 0 train_2_6.txt test_2_6.txt >>result_0_2_6.txt
./EmotionRecognizationClassifier.exe -t 0 train_3_4.txt test_3_4.txt >>result_0_3_4.txt
./EmotionRecognizationClassifier.exe -t 0 train_3_5.txt test_3_5.txt >>result_0_3_5.txt
./EmotionRecognizationClassifier.exe -t 0 train_3_6.txt test_3_6.txt >>result_0_3_6.txt
./EmotionRecognizationClassifier.exe -t 0 train_4_5.txt test_4_5.txt >>result_0_4_5.txt
./EmotionRecognizationClassifier.exe -t 0 train_4_6.txt test_4_6.txt >>result_0_4_6.txt
./EmotionRecognizationClassifier.exe -t 0 train_5_6.txt test_5_6.txt >>result_0_5_6.txt

./EmotionRecognizationClassifier.exe -t 1 train_1_2.txt test_1_2.txt >>result_1_1_2.txt
./EmotionRecognizationClassifier.exe -t 1 train_1_3.txt test_1_3.txt >>result_1_1_3.txt
./EmotionRecognizationClassifier.exe -t 1 train_1_4.txt test_1_4.txt >>result_1_1_4.txt
./EmotionRecognizationClassifier.exe -t 1 train_1_5.txt test_1_5.txt >>result_1_1_5.txt
./EmotionRecognizationClassifier.exe -t 1 train_1_6.txt test_1_6.txt >>result_1_1_6.txt
./EmotionRecognizationClassifier.exe -t 1 train_2_3.txt test_2_3.txt >>result_1_2_3.txt
./EmotionRecognizationClassifier.exe -t 1 train_2_4.txt test_2_4.txt >>result_1_2_4.txt
./EmotionRecognizationClassifier.exe -t 1 train_2_5.txt test_2_5.txt >>result_1_2_5.txt
./EmotionRecognizationClassifier.exe -t 1 train_2_6.txt test_2_6.txt >>result_1_2_6.txt
./EmotionRecognizationClassifier.exe -t 1 train_3_4.txt test_3_4.txt >>result_1_3_4.txt
./EmotionRecognizationClassifier.exe -t 1 train_3_5.txt test_3_5.txt >>result_1_3_5.txt
./EmotionRecognizationClassifier.exe -t 1 train_3_6.txt test_3_6.txt >>result_1_3_6.txt
./EmotionRecognizationClassifier.exe -t 1 train_4_5.txt test_4_5.txt >>result_1_4_5.txt
./EmotionRecognizationClassifier.exe -t 1 train_4_6.txt test_4_6.txt >>result_1_4_6.txt
./EmotionRecognizationClassifier.exe -t 1 train_5_6.txt test_5_6.txt >>result_1_5_6.txt

./EmotionRecognizationClassifier.exe -t 2 train_1_2.txt test_1_2.txt >>result_2_1_2.txt
./EmotionRecognizationClassifier.exe -t 2 train_1_3.txt test_1_3.txt >>result_2_1_3.txt
./EmotionRecognizationClassifier.exe -t 2 train_1_4.txt test_1_4.txt >>result_2_1_4.txt
./EmotionRecognizationClassifier.exe -t 2 train_1_5.txt test_1_5.txt >>result_2_1_5.txt
./EmotionRecognizationClassifier.exe -t 2 train_1_6.txt test_1_6.txt >>result_2_1_6.txt
./EmotionRecognizationClassifier.exe -t 2 train_2_3.txt test_2_3.txt >>result_2_2_3.txt
./EmotionRecognizationClassifier.exe -t 2 train_2_4.txt test_2_4.txt >>result_2_2_4.txt
./EmotionRecognizationClassifier.exe -t 2 train_2_5.txt test_2_5.txt >>result_2_2_5.txt
./EmotionRecognizationClassifier.exe -t 2 train_2_6.txt test_2_6.txt >>result_2_2_6.txt
./EmotionRecognizationClassifier.exe -t 2 train_3_4.txt test_3_4.txt >>result_2_3_4.txt
./EmotionRecognizationClassifier.exe -t 2 train_3_5.txt test_3_5.txt >>result_2_3_5.txt
./EmotionRecognizationClassifier.exe -t 2 train_3_6.txt test_3_6.txt >>result_2_3_6.txt
./EmotionRecognizationClassifier.exe -t 2 train_4_5.txt test_4_5.txt >>result_2_4_5.txt
./EmotionRecognizationClassifier.exe -t 2 train_4_6.txt test_4_6.txt >>result_2_4_6.txt
./EmotionRecognizationClassifier.exe -t 2 train_5_6.txt test_5_6.txt >>result_2_5_6.txt

./EmotionRecognizationClassifier.exe -t 3 train_1_2.txt test_1_2.txt >>result_3_1_2.txt
./EmotionRecognizationClassifier.exe -t 3 train_1_3.txt test_1_3.txt >>result_3_1_3.txt
./EmotionRecognizationClassifier.exe -t 3 train_1_4.txt test_1_4.txt >>result_3_1_4.txt
./EmotionRecognizationClassifier.exe -t 3 train_1_5.txt test_1_5.txt >>result_3_1_5.txt
./EmotionRecognizationClassifier.exe -t 3 train_1_6.txt test_1_6.txt >>result_3_1_6.txt
./EmotionRecognizationClassifier.exe -t 3 train_2_3.txt test_2_3.txt >>result_3_2_3.txt
./EmotionRecognizationClassifier.exe -t 3 train_2_4.txt test_2_4.txt >>result_3_2_4.txt
./EmotionRecognizationClassifier.exe -t 3 train_2_5.txt test_2_5.txt >>result_3_2_5.txt
./EmotionRecognizationClassifier.exe -t 3 train_2_6.txt test_2_6.txt >>result_3_2_6.txt
./EmotionRecognizationClassifier.exe -t 3 train_3_4.txt test_3_4.txt >>result_3_3_4.txt
./EmotionRecognizationClassifier.exe -t 3 train_3_5.txt test_3_5.txt >>result_3_3_5.txt
./EmotionRecognizationClassifier.exe -t 3 train_3_6.txt test_3_6.txt >>result_3_3_6.txt
./EmotionRecognizationClassifier.exe -t 3 train_4_5.txt test_4_5.txt >>result_3_4_5.txt
./EmotionRecognizationClassifier.exe -t 3 train_4_6.txt test_4_6.txt >>result_3_4_6.txt
./EmotionRecognizationClassifier.exe -t 3 train_5_6.txt test_5_6.txt >>result_3_5_6.txt